work around bug in Vivado 2018.2 with Ubuntu 16.04
Causing compilation to error with:

    error: ‘::max_align_t’ has not been declared
        using ::max_align_t;